#include "core/DesireList.hpp"

#include <random>
#include <vector>

namespace married {
namespace {
const std::vector<std::string> kDesires = {
    "to become a programmer",        "to help people",
    "to travel the world",           "to make a difference in the world",
    "to find love",                  "to learn a new language",
    "to start a business",           "to write a book",
    "to solve a world problem",      "to become a doctor",
    "to become a lawyer",            "to become a teacher",
    "to become a scientist",         "to become an artist",
    "to become an athlete",          "to become a musician",
    "to become a writer",            "to become an entrepreneur",
    "to become a philanthropist",    "to become a politician",
    "to become a world leader",      "to become a unicorn",
    "to become a superhero",         "to become a billionaire",
    "to become immortal",            "to become a god",
    "to build a space habitat",      "to plant a million trees",
    "to design a new language",      "to compose a symphony",
    "to paint a masterpiece",        "to run a marathon",
    "to sail around the world",      "to climb Everest",
    "to discover a new species",     "to cure a disease",
    "to open a shelter",             "to mentor young people",
    "to invent clean energy",        "to write a bestseller",
    "to direct a movie",             "to act on Broadway",
    "to craft handmade furniture",   "to brew perfect coffee",
    "to roast the best beans",       "to start a charity",
    "to fly a plane",                "to pilot a submarine",
    "to learn astrophysics",         "to master philosophy",
    "to study ancient history",      "to be a historian",
    "to create a video game",        "to build robots",
    "to explore the ocean",          "to trek the Sahara",
    "to host a podcast",             "to cook like a chef",
    "to open a bakery",              "to become a barista",
    "to design sustainable homes",   "to engineer bridges",
    "to be a firefighter",           "to be a paramedic",
    "to be a pilot",                 "to be an astronaut",
    "to write poetry",               "to become a librarian",
    "to be a diplomat",              "to be an ambassador",
    "to learn sign language",        "to master chess",
    "to become a data scientist",    "to build AI ethically",
    "to teach kids coding",          "to fund scholarships",
    "to protect wildlife",           "to document nature",
    "to be a park ranger",           "to sculpt marble",
    "to build violins",              "to become a luthier",
    "to design fashion",             "to run a vineyard",
    "to restore old cars",           "to collect art",
    "to become a sommelier",         "to be a chocolatier",
    "to start a food truck",         "to open a jazz club",
    "to sing on stage",              "to dance professionally",
    "to choreograph a show",         "to write screenplays",
    "to build tiny houses",          "to go zero waste",
    "to live off grid",              "to be carbon neutral",
    "to teach meditation",           "to practice yoga",
    "to build a community garden",   "to coach a team",
    "to be a life coach",            "to guide mountain tours",
    "to photograph the night sky",   "to be a travel blogger",
    "to record an album",            "to produce music",
    "to mix electronic tracks",      "to collect vinyl",
    "to repair bicycles",            "to craft leather goods",
    "to forge knives",               "to blow glass",
    "to knit sweaters",              "to weave tapestries",
    "to design board games",         "to be a magician",
    "to build drones",               "to do parkour",
    "to skydive often",              "to paraglide daily",
    "to surf big waves",             "to scuba dive reefs",
    "to volunteer globally",         "to fund clean water",
    "to map the stars",              "to write a science column",
    "to restore frescoes",           "to curate a museum",
    "to analyze fossils",            "to study volcanos",
    "to track hurricanes",           "to predict climate",
    "to craft perfumes",             "to design gardens",
    "to build kinetic art",          "to code open source",
    "to manage a startup",           "to invest in impact",
    "to run an incubator",           "to teach entrepreneurship",
    "to organize hackathons",        "to create documentaries",
    "to host workshops",             "to translate literature",
    "to master calligraphy",         "to learn 10 languages",
    "to adopt many pets",            "to foster children",
    "to build a sanctuary",          "to drive a racecar",
    "to craft watches",              "to design sneakers",
    "to 3D-print houses",            "to build satellites",
    "to lead expeditions",           "to open a makerspace",
    "to write a memoir",             "to edit a magazine",
    "to brew craft beer",            "to roast cocoa beans",
    "to build smart farms",          "to map coral reefs",
    "to mine an asteroid",           "to terraform Mars",
    "to be a mythbuster",            "to design playgrounds",
    "to engineer prosthetics",       "to build exoskeletons"};
}  // namespace

std::string randomDesire() {
    thread_local std::mt19937 gen{std::random_device{}()};
    std::uniform_int_distribution<std::size_t> dist(0, kDesires.size() - 1);
    return kDesires[dist(gen)];
}

}  // namespace married
